CREATE SCHEMA IF NOT EXISTS EZ_FASTFOOD_ORDER;


CREATE TABLE IF NOT EXISTS EZ_FASTFOOD_ORDER.ORDER (
    id BIGSERIAL PRIMARY KEY,
    order_number VARCHAR(255),
    user_id INT NULL,
    user_name VARCHAR(255),
    order_time TIMESTAMP WITH TIME ZONE,
    total_price DECIMAL(10, 2),
    order_status VARCHAR(50) DEFAULT 'WAITING_PAYMENT',
    completed_time TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS EZ_FASTFOOD_ORDER.ORDER_ITEMS (
    id BIGSERIAL PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT,
    price DECIMAL,
    FOREIGN KEY (order_id) REFERENCES EZ_FASTFOOD_ORDER.ORDER(id)
);