apiVersion: v1
kind: ServiceAccount
metadata:
  name: ezfastfood-order-sa  # Nome do ServiceAccount
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::637423288778:role/eks-irsa-sqs-role
